### ISSUE TITLE
Logos and graphics

### ISSUE THREAD

**Issue by dintid** [Ultimaker/Ultimaker2Plus#1]
Hello,
I wondered if there are some reasons the logo (robot for the sides) and other graphics like SD and on/off is not included in the repositories as high res png/pdf files?

They might of course be under some different license, but please let us know :)
I found the "Ultimaker" logo using your forums but/and I can't browse the file-structure, so can't look for other usefull graphics files
https://ultimaker.com/download/2381/Ultimaker%20Corporate%20Design%20Manual.pdf

Looking forward to hearing from you (mailed a week ago, but havn't heard back)

Cheers

**Comment by harmawoldhuis** [comment]
Hello dintid,

We put the files we use to order the parts in the repositories. It could be that it isn't very high resolution. Please find attached the high res png files of our logo with robot. You can cut the robot from there. 
If you need any other high res grafics, please let me know.

Kind regards, 
Harma Woldhuis
![ultimaker logo - 4000px](https://cloud.githubusercontent.com/assets/5518443/23851317/5e9f15dc-07e3-11e7-9a4f-1267a5c68298.png)

**Comment by daid** [comment]
There is also the font which contains these as vectors:
http://software.ultimaker.com/ULTIMAKER-FONT.TTF
(Note that these are part of our trademark. Which is independent of the CC licence, and I'm not a lawyer so I cannot say what the implications of this are)

**Comment by Ghostkeeper** [comment]
I traced the logo once as SVG.
[ultimaker.svg.zip](https://github.com/Ultimaker/Ultimaker2Plus/files/840968/ultimaker.svg.zip)

**Comment by dintid** [comment]
Thanks!
Is there any files with the SD-card + the enclosing bracket and on/off?

**Comment by daid** [comment]
Just wondering, what are you planning to do with these?

**Comment by dintid** [comment]
Just trying to make my machine as close as possible to the real deal :)
