### ISSUE TITLE
Duplicate component in file "Main assembly Ultimaker 2+"

### ISSUE THREAD

**Issue by Spirou42** [Ultimaker/Ultimaker2Plus#2]
Inside the file: "Main assembly Ultimaker 2+" there is a duplicate component in the sub component: "Feeder left_fil flow sens/fedder handler" there are two components named "1967-M_part B (1968)" and "1968-J_part B (1968)". Those two components are identical and occupy the same space.

![screen shot 2017-07-24 at 21 34 16](https://user-images.githubusercontent.com/759145/28541087-f6431e5a-70b7-11e7-9e5b-f3afaa4fec60.png)

**Comment by BagelOrb** [comment]
Paging @Bas-van-Deursen

**Comment by harmawoldhuis** [comment]
updated assembly, removed obsolete part
