### ISSUE TITLE
top and bottom clips Advanced 3D Printing Kit missing

### ISSUE THREAD

**Issue by wybren1971** [Ultimaker/Ultimaker2Plus#3]
Hello,

I was looking through the repro of de ultimaker 2 and 2+ but could not find the step file for the top and bottom clip of the front enclosure coming with the advanced 3d printing kit..

Is it possible to add these to the repository or in an repository of their own?

thanks in advance
Wybren

**Comment by harmawoldhuis** [comment]
Hello Wybren,

I've just added the files to the repository. 

Kind regards,
Harma Woldhuis

**Comment by wybren1971** [comment]
Super Harma,

Bedankt voor de snelle actie.

Groet Wybren
